name: Despliegue en GKE

on:
  push:
    branches: [ main, hotfix ]

  pull_request:
    branches: [ main, hotfix ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  KUBE_NAMESPACE: smartmarketplace
  KUBE_DEPLOYMENT_NAME: smp-app
  KUBE_SERVICE_NAME: smp-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del cÃ³digo fuente
        uses: actions/checkout@v2

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Autenticar con Google Cloud
        run: |
          echo "${{ secrets.GCLOUD_AUTH }}" | base64 --decode > ${HOME}/gcloud-auth.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-auth.json

      - name: Seleccionar cuenta de Google Cloud
        run: gcloud config set account ACCOUNT
        env:
          ACCOUNT: david.alberto.guzman@correounivalle.edu.co

      - name: Autenticar con GKE
        run: |
          gcloud container clusters get-credentials smartmarketplace-2023 --zone=us-central1

      - name: Despliegue en GKE
        run: |
          kubectl apply -f  smp-app-deployments.yaml -n smartmarketplace
          kubectl apply -f  smp-app-istio.yaml -n smartmarketplace
          kubectl apply -f  smp-app-service.yaml -n smartmarketplace
